wicket-datetime/src/main/java/org/apache/wicket/extensions/yui/calendar/DateTimeField.java

Created new factory method for the minutes Textfield

Factory method for the minutes Textfield

---

wicket-core/.settings/org.eclipse.wst.common.project.facet.core.xml
wicket-core/src/main/java/org/apache/wicket/resource/CompositeCssCompressor.java
wicket-core/src/main/java/org/apache/wicket/resource/CompositeJavaScriptCompressor.java
wicket-core/src/main/java/org/apache/wicket/resource/CssUrlReplacementCompressor.java
wicket-core/src/main/java/org/apache/wicket/resource/CssUrlReplacer.java

- Allow multiple ICssCompressors and IJavaScriptCompressors
- CssUrlReplacementCompressor

WICKET-5827 Allow to apply multiple Javascript / CSS compressors

---

wicket-examples/src/main/java/org/apache/wicket/examples/media/Home.css
wicket-examples/src/main/java/org/apache/wicket/examples/media/Home.html
wicket-examples/src/main/java/org/apache/wicket/examples/media/Home.java

Screenshot:
https://issues.apache.org/jira/secure/attachment/12699692/wicket-examples-media-tags.png

WICKET-5819 - Vertical layout for examples

---

wicket-examples/pom.xml

See https://issues.apache.org/jira/browse/WICKET-5825 for more information.

WICKET-5825

---

wicket-core/src/main/java/org/apache/wicket/markup/html/PackageResourceGuard.java
wicket-core/src/test/java/org/apache/wicket/markup/html/PackageResourceGuardTest.java
wicket-core/src/test/java/org/apache/wicket/markup/html/PackageResourceTest.java
wicket-ioc/src/main/java/org/apache/wicket/proxy/LazyInitProxyFactory.java

WICKET-5851 Fix PackageResourceTest and PackageResourceGuardTest under Windows

---

wicket-devutils/src/main/java/org/apache/wicket/devutils/debugbar/DebugBar.java
wicket-devutils/src/main/java/org/apache/wicket/devutils/debugbar/wicket-debugbar.css
wicket-devutils/src/main/java/org/apache/wicket/devutils/debugbar/wicket-debugbar.js

- Add `positionBottom` method to position it at the bottom of the screen
- Remember expanded/collapsed state

Added DebugBar improvements

---

wicket-core/src/main/java/org/apache/wicket/protocol/http/AbstractRequestLogger.java
wicket-core/src/main/java/org/apache/wicket/protocol/http/IRequestLogger.java
wicket-core/src/test/java/org/apache/wicket/protocol/http/AbstractRequestLoggerTest.java

As discussed in https://issues.apache.org/jira/browse/WICKET-5914

Added possibility to log custom userData in the RequestLogger

---

wicket-core/src/main/java/org/apache/wicket/ajax/res/js/wicket-ajax-jquery.js

in order to match AbstractDefaultAjaxBehavior.FAILURE_HANDLER_FUNCTION_TEMPLATE

WICKET-6084: supply additional args to ajax request fh function

---

wicket-core/src/main/java/org/apache/wicket/model/IModel.java
wicket-core/src/test/java/org/apache/wicket/model/IModelTest.java

I implemented the changes proposed in https://issues.apache.org/jira/browse/WICKET-6203.
Please don't hesitate to yell at me, if I did something wrong or something is missing. I tried to conform to the contribution guidelines.

WICKET-6203 rework IModel#mapWith

---

wicket-extensions/src/main/java/org/apache/wicket/extensions/ajax/AjaxDownloadBehavior.java
wicket-extensions/src/main/java/org/apache/wicket/extensions/ajax/wicket-ajaxdownload.js

I would appreciate if someone can review my changes

[WICKET-6491] ajax download seems to work under both IE11 and Edge

---

wicket-util/src/main/java/org/apache/wicket/util/convert/MaskConverter.java
wicket-util/src/main/java/org/apache/wicket/util/crypt/Base64.java
wicket-util/src/main/java/org/apache/wicket/util/diff/myers/package.html
wicket-util/src/main/java/org/apache/wicket/util/diff/package.html
wicket-util/src/main/java/org/apache/wicket/util/encoding/UrlDecoder.java
wicket-util/src/main/java/org/apache/wicket/util/encoding/UrlEncoder.java
wicket-util/src/main/java/org/apache/wicket/util/io/FullyBufferedReader.java
wicket-util/src/main/java/org/apache/wicket/util/lang/Objects.java
wicket-util/src/main/java/org/apache/wicket/util/string/Strings.java

Starting small with contributions :)

Fix JavaDoc warnings in wicket-util

---

pom.xml

PR to upgrade various dependencies. Any chance we can see a 8.5.0 in May?

[WICKET-6665] Upgrade various dependencies

---

wicket-examples/src/main/java/org/apache/wicket/examples/ajax/builtin/BasePage.java
wicket-examples/src/main/java/org/apache/wicket/examples/ajax/builtin/Index.java
wicket-examples/src/main/java/org/apache/wicket/examples/ajax/builtin/OnChangeAjaxBehaviorPage.html
wicket-examples/src/main/java/org/apache/wicket/examples/ajax/builtin/OnChangeAjaxBehaviorPage.java
wicket-examples/src/main/java/org/apache/wicket/examples/ajax/builtin/OnChangeAjaxBehaviorPage.properties

The demo was misleading. I thought it will just display what I typed in the label, I typed 555 and though it's broken.  Updated the demo to be more obvious.

Improve OnChangeAjaxBehavior demo

---

wicket-core/src/main/java/org/apache/wicket/ajax/res/js/wicket-ajax-jquery.js

tested using latest Chrome/Chromium/FF/IE11

[WICKET-6748] CSS onload/onerror is rewritten

---

wicket-core/src/main/java/org/apache/wicket/Component.java
wicket-core/src/main/java/org/apache/wicket/request/component/IRequestableComponent.java
wicket-core/src/test/java/org/apache/wicket/behavior/BehaviorTest.java
wicket-core/src/test/java/org/apache/wicket/behavior/ImmutableBehaviorIdsTest.java

This PR suggest a minor change to the contract of IRequestComponent.getBehaviorId to prepare for a refactoring of the component internals.

WICKET-6774: minor change to contract of Component.getBehaviorId

---

wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/WebSocketSettings.java
wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/util/tester/WebSocketTester.java

Use different thread executors when pushing WebSocketPushMessage in http worker thread and non-worker thread

WICKET-6791 Offload WebSocket push when initiated in Wicket request cycle

---

wicket-user-guide/src/main/asciidoc/security/security_10.adoc
wicket-user-guide/src/main/asciidoc/security/security_5.adoc
wicket-user-guide/src/main/asciidoc/security/security_9.adoc
wicket-user-guide/src/main/asciidoc/single.adoc

Hello again Wicket devs! 
We're super excited to have contributed to Wicket, adding [Fetch Metadata support ](https://github.com/apache/wicket/pull/439) and [COOP / COEP support](https://github.com/apache/wicket/pull/442/)! We have made changes to the user guide describing the changes so users can easily configure and enable these features!

Documentation for Fetch Metadata and Coop/Coep Suppport 

---

wicket-core/src/main/java/org/apache/wicket/ajax/res/js/wicket-ajax-jquery.js

According to https://developer.mozilla.org/en-US/docs/Web/API/DOMParser native implementation is available since IE 9/10

WICKET-6846 remove activex

---

pom.xml
testing/wicket-threadtest/src/site/site.xml
wicket-auth-roles/src/site/site.xml
wicket-core/src/site/site.xml
wicket-examples/src/site/site.xml
wicket-extensions/src/site/site.xml
wicket-guice/src/site/site.xml
wicket-ioc/src/site/site.xml
wicket-jmx/src/site/site.xml
wicket-objectsizeof-agent/src/site/site.xml
wicket-spring/src/site/site.xml
wicket-velocity/src/site/site.xml

The only issue I'm observing so far: All links to JDK classes points to Java8 API .....

WICKET-6884: javadoc:aggregate seems to work locally

---

wicket-extensions/src/main/java/org/apache/wicket/extensions/ajax/markup/html/AjaxEditableChoiceLabel.java
wicket-extensions/src/main/java/org/apache/wicket/extensions/ajax/markup/html/repeater/data/table/AjaxFallbackDefaultDataTable.java
wicket-extensions/src/main/java/org/apache/wicket/extensions/markup/html/repeater/data/table/NavigationToolbar.java
wicket-extensions/src/main/java/org/apache/wicket/extensions/markup/html/repeater/data/table/NavigatorLabel.java

Corresponding changes to 
https://github.com/apache/wicket/pull/481
But for mater. As agreed here we just change return type of factory method for label.

[WICKET-6935] several minor datatable improvements

---

pom.xml
wicket-core/src/main/java/module-info.java
wicket-core/src/main/java/org/apache/wicket/markup/html/form/Form.java
wicket-core/src/main/java/org/apache/wicket/markup/html/form/upload/FileUpload.java
wicket-core/src/main/java/org/apache/wicket/markup/html/form/upload/FileUploadField.java
wicket-core/src/main/java/org/apache/wicket/markup/html/form/upload/MultiFileUploadField.java
wicket-core/src/main/java/org/apache/wicket/protocol/http/IMultipartWebRequest.java
wicket-core/src/main/java/org/apache/wicket/protocol/http/mock/MockHttpServletRequest.java
wicket-core/src/main/java/org/apache/wicket/protocol/http/servlet/MultipartServletWebRequest.java
wicket-core/src/main/java/org/apache/wicket/protocol/http/servlet/MultipartServletWebRequestImpl.java
wicket-core/src/main/java/org/apache/wicket/protocol/http/servlet/ServletPartFileItem.java
wicket-core/src/main/java/org/apache/wicket/protocol/http/servlet/ServletWebRequest.java
wicket-core/src/test/java/org/apache/wicket/markup/html/form/upload/FileUploadTest.java
wicket-examples/src/main/java/org/apache/wicket/examples/ajax/builtin/FileUploadPage.java
wicket-extensions/src/main/java/module-info.java
wicket-extensions/src/main/java/org/apache/wicket/extensions/ajax/AjaxFileDropBehavior.java
wicket-extensions/src/main/java/org/apache/wicket/extensions/ajax/markup/html/form/upload/UploadStatusResource.java
wicket-util/pom.xml
wicket-util/src/main/java/javax/servlet/ServletContext.java
wicket-util/src/main/java/module-info.java

commons-fileupload2 supports Jakarta APIs

WICKET-6915 Upgrade to commons-fileupload2

---

README.md

While trying to build Wicket from source after a long long time again, I believe I have spotted a few outdated infos and other minor issues in the README of the project. Hope to have corrected these accordingly here.

Some minor corrections and updates of the README file

---

wicket-core/src/main/java/module-info.java

Fix module error:
uses org.apache.wicket.IInitializer;

WICKET-6957: Update module-info.java

---

wicket-examples/src/main/java/org/apache/wicket/examples/websocket/JSR356Application.java
wicket-examples/src/main/java/org/apache/wicket/examples/websocket/charts/ChartUpdater.java
wicket-examples/src/main/java/org/apache/wicket/examples/websocket/progress/ProgressUpdater.java
wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/WebSocketSettings.java
wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/api/AbstractWebSocketConnection.java
wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/api/AbstractWebSocketProcessor.java
wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/api/IWebSocketConnection.java
wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/api/IWebSocketRequestHandler.java
wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/api/WebSocketPushBroadcaster.java
wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/api/WebSocketRequestHandler.java
wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/api/WebSocketResponse.java
wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/util/tester/TestWebSocketConnection.java
wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/util/tester/TestWebSocketProcessor.java
wicket-native-websocket/wicket-native-websocket-javax/src/main/java/org/apache/wicket/protocol/ws/javax/JavaxWebSocketProcessor.java

This PR adds the capability to configure application to send web socket push messages in an asynchronous manner.

{WICKET-6969} allow asynchronous pushing of messages.

---

wicket-util/src/main/java/org/apache/wicket/util/io/Connections.java

Adds null check.
https://issues.apache.org/jira/browse/WICKET-6971
https://lists.apache.org/thread/v3hbwsp3qs0rsnbsj6jp34662hrbjcgk

[WICKET-6971] NullPointerException in ModificationWatcher

---

wicket-user-guide/src/main/asciidoc/security/security_5.adoc

Links to issue https://issues.apache.org/jira/browse/WICKET-7007

Fix apache/wicket#WICKET-7007

---

wicket-core/src/main/java/org/apache/wicket/util/cookies/CookieDefaults.java
wicket-examples/src/main/java/org/apache/wicket/examples/ajax/builtin/AjaxDownloadPage.java
wicket-extensions/src/main/java/org/apache/wicket/extensions/ajax/AjaxDownloadBehavior.java
wicket-extensions/src/main/java/org/apache/wicket/extensions/ajax/wicket-ajaxdownload.js

This seems to fix the FF warning.

[WICKET-7037] add SameSite attribute to cookie.

---

wicket-core/src/main/java/org/apache/wicket/csp/CSPRequestCycleListener.java

move generation of CSP related header(s) to onRequestHandlerExecuted

[WICKET-7028] move generation of CSP related header(s) to onRequestHandlerExecuted

---

wicket-core/src/main/java/org/apache/wicket/ajax/AjaxRequestHandler.java

We currently buffer ajax responses twice, first wrapping them in a `StringResponse` and then in an `AppendingStringBuffer`. This whole wrapping is really only necessary when the application has one or more `IResponseFilter`. By default, Wicket applications running in deployment mode *do not have* any response filters.
This PR adjusts `AjaxRequestHandler#respond` to write the page update directly to the response if no filters are active. This should drastically reduce allocations for large ajax responses.
https://issues.apache.org/jira/browse/WICKET-7046

WICKET-7046 Avoid buffering in AjaxRequestHandler when no response filters active

---

wicket-core/src/main/java/org/apache/wicket/ajax/AjaxUtils.java
wicket-core/src/main/java/org/apache/wicket/markup/html/form/Form.java
wicket-core/src/main/java/org/apache/wicket/markup/html/form/upload/resource/AbstractFileUploadResource.java
wicket-core/src/main/java/org/apache/wicket/markup/html/form/upload/resource/FileUploadResourceReference.java
wicket-core/src/main/java/org/apache/wicket/markup/html/form/upload/resource/FileUploadToResourceField.java
wicket-core/src/main/java/org/apache/wicket/markup/html/form/upload/resource/FileUploadToResourceField.js
wicket-core/src/main/java/org/apache/wicket/markup/html/form/upload/resource/FileUploadToResourceField.properties
wicket-core/src/main/java/org/apache/wicket/markup/html/form/upload/resource/FolderUploadsFileManager.java
wicket-core/src/main/java/org/apache/wicket/markup/html/form/upload/resource/IUploadsFileManager.java
wicket-examples/src/main/java/org/apache/wicket/examples/upload/UploadApplication.java
wicket-examples/src/main/java/org/apache/wicket/examples/upload/UploadPage.java
wicket-examples/src/main/java/org/apache/wicket/examples/upload/UploadToResourcePage.html
wicket-examples/src/main/java/org/apache/wicket/examples/upload/UploadToResourcePage.java
wicket-examples/src/main/resources/org/apache/wicket/examples/homepage/HomePage.html
wicket-examples/src/main/resources/org/apache/wicket/examples/style.css
wicket-extensions/src/main/java/org/apache/wicket/extensions/ajax/markup/html/form/upload/UploadProgressBar.java
wicket-extensions/src/main/java/org/apache/wicket/extensions/ajax/markup/html/form/upload/progressbar.js

This PR adds:
- uploading file(s) into a mounted resource.
- Improve upload progress bar to work witth uploading to a mounted resource.
[Screencast from 2023-04-11 14-02-33.webm](https://user-images.githubusercontent.com/462655/231141442-cc82962e-131e-42f4-93a5-9fe145b366a5.webm)

[WICKET-7033] upload to a mounted resource

---

wicket-commons-fileupload/src/main/java/org/apache/wicket/commons/fileupload2/pub/FileUploadByteCountLimitException.java
wicket-core/src/main/java/org/apache/wicket/markup/html/form/Form.java
wicket-core/src/main/java/org/apache/wicket/markup/html/form/upload/resource/AbstractFileUploadResource.java
wicket-core/src/test/java/org/apache/wicket/markup/html/form/upload/FileUploadErrorTest.java
wicket-core/src/test/java/org/apache/wicket/markup/html/form/upload/FileUploadFieldTest.java
wicket-core/src/test/java/org/apache/wicket/markup/html/form/upload/FileUploadServletPartTest.java
wicket-core/src/test/java/org/apache/wicket/markup/html/form/upload/MultiFileUploadFieldTest.java

[WICKET-7051] reorder exception handling in Form + re-enable disabled te

[WICKET-7051] reorder exception handling in Form + re-enable disabled tests

---

wicket-extensions/src/main/java/org/apache/wicket/extensions/ajax/markup/html/autocomplete/AutoCompleteBehavior.java
wicket-extensions/src/main/java/org/apache/wicket/extensions/ajax/markup/html/autocomplete/wicket-autocomplete.js

- Add aria-autocomplete = list to Component bound to AutoCompleteBehavior
- Add aria-live = polite to wicket-aa Autocomplete Choice div

[WICKET-7039] Improve A11y of Autocomplete

---

pom.xml
wicket-core/pom.xml
wicket-extensions/pom.xml
wicket-extensions/src/main/java/org/apache/wicket/extensions/markup/html/repeater/tree/theme/windows/theme.css

Unfortunately good old `yuicompressor-maven-plugin` (latest release from `Nov 23, 2014`) breaks CSS files while minimizing :(
for my previous RTL related fix it did following change `calc(100% + 54px)` -> `calc(100%+54px)` which made expression invalid :((
There were some other breaking changed, this is why I've turned-off CSS compression for Apache OpenMeetings long time ago
I've replaced it with `resources-optimizer-maven-plugin` which seems to 
- be supported
- works as expected

[WICKET-7068] Tree rtl styling

---

wicket-core-tests/src/test/java/org/apache/wicket/core/util/cookies/CookieUtilsTest.java
wicket-core/src/main/java/org/apache/wicket/util/cookies/CookieUtils.java
wicket-extensions/src/main/java/org/apache/wicket/extensions/ajax/AjaxDownloadBehavior.java

There was one more occurrence where app crashed because of running in Servlet 5 container

WICKET-7089: Fix setting SameSite cookie attribute on Servlet 5

---

wicket-core-tests/src/test/java/org/apache/wicket/csp/CSPSettingRequestCycleListenerTest.java
wicket-core/src/main/java/org/apache/wicket/csp/FixedCSPValue.java

WICKET-7094: Add missing scheme values of CSP

---

wicket-core-tests/src/test/java/org/apache/wicket/markup/resolver/AutoLinkResolverTest.java
wicket-core/src/main/java/org/apache/wicket/markup/resolver/AutoLinkResolver.java

https://issues.apache.org/jira/browse/WICKET-7096

WICKET-7096: add missing nonce to auto linked resources

---

wicket-core/src/main/java/org/apache/wicket/csp/CSPDirective.java

Add support for missing CSP directives [https://issues.apache.org/jira/browse/WICKET-7093](url)

WICKET-7093: Adding "form-action" to the CSP Directives

---

wicket-devutils/src/main/java/org/apache/wicket/devutils/inspector/LiveSessionsPage.java

Fix Error when Bytes Constructor is called with -1

[WICKET-7102]

---

wicket-extensions/src/main/java/org/apache/wicket/extensions/ajax/markup/html/modal/ModalDialog.java
wicket-extensions/src/test/java/org/apache/wicket/extensions/ajax/markup/html/modal/ModalDialogTest.java

see https://issues.apache.org/jira/browse/WICKET-7103

WICKET-7103

---

wicket-core/src/main/java/org/apache/wicket/markup/html/form/GroupedDropDownChoice.java
wicket-core/src/test/java/org/apache/wicket/markup/html/form/GroupedDropDownChoiceTest.java
wicket-core/src/test/java/org/apache/wicket/markup/html/form/GroupedDropDownChoiceTestPage.html
wicket-core/src/test/java/org/apache/wicket/markup/html/form/GroupedDropDownChoiceTestPage.java
wicket-core/src/test/java/org/apache/wicket/markup/html/form/GroupedDropDownChoiceTestPage_0_false_expected.html
wicket-core/src/test/java/org/apache/wicket/markup/html/form/GroupedDropDownChoiceTestPage_0_true_expected.html
wicket-core/src/test/java/org/apache/wicket/markup/html/form/GroupedDropDownChoiceTestPage_null_false_expected.html
wicket-core/src/test/java/org/apache/wicket/markup/html/form/GroupedDropDownChoiceTestPage_null_true_expected.html
wicket-examples/src/main/java/org/apache/wicket/examples/compref/DropDownChoicePage.html
wicket-examples/src/main/java/org/apache/wicket/examples/compref/DropDownChoicePage.java

[Screencast from 2024-05-06 09-26-47.webm](https://github.com/apache/wicket/assets/462655/197ed293-7d78-4a30-96a5-526138aa6b9b)

[WICKET-7109] add some ready to use DropDownChoice supporting grouping

---

wicket-util/src/main/java/org/apache/wicket/util/resource/XSLTResourceStream.java

fix: configurable transformer formatting

---

wicket-core-tests/src/test/java/org/apache/wicket/LocalizerTest.java
wicket-core-tests/src/test/java/org/apache/wicket/core/util/license/ApacheLicenceHeaderTest.java

Also fixed code warnings. The actual changes that fix the issues are on the following lines of the new versions:
* `LocalizerTest`: 217-220
* `ApacheLicenceHeaderTest`: 147-151

WICKET-7117 Fixed tests in ApacheLicenceHeaderTest and LocalizerTest

---

.github/workflows/maven.yml
pom.xml

* Update some Ubuntu packages for 24.04
* Update Maven to 3.9.9
* Build with JDK 23 instead of 22

Try to fix the build at Github Actions CI

---

wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/WebSocketSettings.java

The non-JSR-356 impls were removed long time ago in favour of the standard one.

WICKET-7150: Do not check whether the javax impl is in use

---

wicket-examples/Dockerfile

Changes:
* Tomcat 10.1 / JRE17 for wicket-examples

feat: adjusted examples to tomcat 10.1 jre17
