apache/wicket

- wicket-core/src/main/java/org/apache/wicket/resource/CompositeCssCompressor.java
- wicket-core/src/main/java/org/apache/wicket/resource/CssUrlReplacer.java
+ CssUrlReplacer / CompositeCssCompressor must implement ICssCompressor, otherwise they can't be added to getResourceSettings().setCssCompressor(..)
+ replaced content of IScopeAwareTextResourceProcessor should be stored compressed = processor.process(compressed, scope, name);
> WICKET-5827 bugfixes 6.x

- wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/AbstractUpgradeFilter.java
- wicket-native-websocket/wicket-native-websocket-javax/src/main/java/org/apache/wicket/protocol/ws/javax/JavaxWebSocketFilter.java
- wicket-native-websocket/wicket-native-websocket-jetty/src/main/java/org/apache/wicket/protocol/ws/jetty/Jetty7WebSocketFilter.java
- wicket-native-websocket/wicket-native-websocket-jetty9/src/main/java/org/apache/wicket/protocol/ws/jetty9/Jetty9WebSocketFilter.java
- wicket-native-websocket/wicket-native-websocket-tomcat/src/main/java/org/apache/wicket/protocol/ws/tomcat7/Tomcat7WebSocketFilter.java
Currently it's not possible to use the Websocket filters in pure java-based servlet 3.0 configurations without subclassing the Filter and  overriding the `getApplicationFactory` method. 
This PR adds the `WicketFilter(Webapplication application)` constructor to all websocket filters.
> Added constructor to Websocket filters 

- pom.xml
- wicket-guice/src/main/java/org/apache/wicket/guice/GuiceFieldValueFactory.java
- wicket-guice/src/main/java/org/apache/wicket/guice/GuiceProxyTargetLocator.java
- wicket-guice/src/test/java/org/apache/wicket/guice/AbstractInjectorTest.java
- wicket-guice/src/test/java/org/apache/wicket/guice/EvilTestService.java
- wicket-guice/src/test/java/org/apache/wicket/guice/JavaxInjectGuiceInjectorTest.java
- wicket-guice/src/test/java/org/apache/wicket/guice/JavaxInjectTestComponent.java
- wicket-guice/src/test/java/org/apache/wicket/guice/TestComponent.java
- wicket-ioc/pom.xml
- wicket-ioc/src/main/java/org/apache/wicket/proxy/LazyInitProxyFactory.java
- wicket-ioc/src/main/java/org/apache/wicket/proxy/ObjenesisProxyFactory.java
This allows creating proxies for concrete classes without a default
constructor.
Guice IoC cache proxies similar to spring
-----
It may need some  more finishing touches, but would something like this be considered for inclusion?
> IoC: Optionally use objensis for proxy creation

- wicket-user-guide/src/docs/guide/modelsforms/modelsforms_3.gdoc
The java code example used two variables with identical name and of different type, not only this would not compile, but the used name could potentially steer wicket beginners in wrong direction of thinking (regarding the matter of topic in this code snippet).
> User Guide - Wicket forms - CompoundPropertyModel - sample java code issues

- wicket-core/src/main/java/org/apache/wicket/pageStore/memory/HttpSessionDataStore.java
- When using Tomcats o.a.c.h.t.SimpleTCPCluster to replicate Sessions
in a Tomcat cluster the o.a.c.h.s.DeltaSession is the default
implementation which handles session replication
- Unfortunately, to calculate its deltas, it assumes that session
attributes are only modified by calling accessor methods (i.e.
DeltaSession.setAttribute(n,v))
- Modifying an existing Object (e.g. wicket's PageTable) in place of
the current session, would not trigger a delta replication
- To make Wicket work with SimpleTCPCluster and DeltaSessions, we will
always rewrite the PageTable into Session by calling setAttribute
> Enable DeltaManager to replicate PageTable in Sessions

- wicket-core/src/main/java/org/apache/wicket/model/IModel.java
I fixed the formatting and provided an idea for implementing flatMap in a lazy fashion.
> idea for lazy flatMap

- wicket-core/src/main/java/org/apache/wicket/markup/html/image/Image.java
...in class Image, so that one can define precisely
how to generate the anticache parameter value.
See https://issues.apache.org/jira/browse/WICKET-6206
> WICKET-6206 Allow overriding of addAntiCacheParameter

- wicket-core/src/main/java/org/apache/wicket/request/cycle/PageRequestHandlerTracker.java
- wicket-core/src/test/java/org/apache/wicket/request/cycle/PageRequestHandlerTrackerTest.java
PageRequestHandlerTracker doesn't work with CryptoMapper.
In mapRequest method in CryptoMapper it is created instance of RequestSettingRequestHandler and PageRequestHandlerTracker doesn't looking for IPageRequestHandler inside IRequestHandlerDelegate.
Reproduce steps:
1 application init method
```java
@Override
public void init() {
super.init();
getRequestCycleListeners().add(new PageRequestHandlerTracker());
setRootRequestMapper(new CryptoMapper(getRootRequestMapper(), this));
}
```
2 Try to get last handler in page or component
```java
@Override
protected void onBeforeRender() {
super.onBeforeRender();
RequestCycle cycle = getRequestCycle();
IPageRequestHandler lastHandler = PageRequestHandlerTracker.getLastHandler(cycle);
System.out.println(lastHandler.getPageClass().getCanonicalName()) …
```
> PageRequestHandlerTracker issue

- wicket-examples/src/main/java/org/apache/wicket/examples/ajaxhellobrowser/AjaxHelloBrowser.java
- wicket-examples/src/main/java/org/apache/wicket/examples/hellobrowser/HelloBrowser.java
DateFormat previously used the jvm's default time zone, which leads to somewhat confusing output on the example page: 'Based on your settings, your time is: 4:46:15 AM EDT (and your time zone is Central European Time)'
After this patch, it shows '10:57:49 AM CEST (and your time zone is Central European Time)' (jvm's default time zone no longer relevant)
> TimeZone handling in examples: apply settings client time zone on DateFormat

- wicket-core/src/main/java/org/apache/wicket/Session.java
- wicket-core/src/test/java/org/apache/wicket/session/SessionInvalidateTest.java
Wicket 6.x fails Session.invalidateNow() after deserialisation (For example, when using Oracle Coherence).
Session.destroy() uses sessionStore. But it is null after deserialisation because sessionStore is transient.
> fix Sesssion invalidate method dose not work after deserialisation

- pom.xml
- testing/wicket-arquillian/pom.xml
I was unable to update 
org.jglue.cdi-unit:cdi-unit and wildfly
It seems code/build modifications are required for this :(
> WICKET-6437: Library versions are updated

- archetypes/quickstart/src/main/resources/archetype-resources/src/main/java/HomePage.html
This also resolves a rendering problem when accessing the quickstart application over HTTPS: the font wasn't loaded from insecure connection.
> Update links to HTTPS in Quickstart application

- wicket-core/src/main/java/org/apache/wicket/model/LambdaModel.java
It is sometimes hard to find which model is misused as ReadOnly model when it should be a ReadWrite one, because the UnsupportedOperationException doesn't provide enough information (some model of some component doesn't support setObject):
```
java.lang.UnsupportedOperationException: setObject(Object) not supported
at org.apache.wicket.model.LambdaModel.setObject(LambdaModel.java:53)
at org.apache.wicket.Component.setDefaultModelObject(Component.java:3122)
at org.apache.wicket.markup.html.form.FormComponent.setModelObject(FormComponent.java:1579)
at org.apache.wicket.markup.html.form.FormComponent.updateModel(FormComponent.java:1097)
```
this PR will make the unsupported stack trace to contain more detailed information like this:
`Caused by: java.lang.UnsupportedOperationException: …
> provide more information on read only LambdaModel setObject exception

- wicket-core/src/main/java/org/apache/wicket/markup/html/form/Form.java
- wicket-core/src/test/java/org/apache/wicket/markup/html/form/FormMethodMismatchTest$FormWithAjaxButtonPage.html
- wicket-core/src/test/java/org/apache/wicket/markup/html/form/FormMethodMismatchTest$FormWithButtonPage.html
- wicket-core/src/test/java/org/apache/wicket/markup/html/form/FormMethodMismatchTest$PlainFormPage.html
- wicket-core/src/test/java/org/apache/wicket/markup/html/form/FormMethodMismatchTest.java
this moves the HTTP method check from onFormSubmitted to
onFormSubmitted(submitter) so that every form submission
performs this check, instead of only non-ajax requests.
also adds tests that verify this.
> WICKET-6526 check HTTP method for all form submissions

- wicket-core/src/main/java/org/apache/wicket/core/util/lang/PropertyResolver.java
- wicket-core/src/main/java/org/apache/wicket/pageStore/AsynchronousDataStore.java
There are two changes made in this pull request to improve some logging statements:
1. There is a possible copy and paste error in the log messages (The logging statement was copied from an old place to a new place, but the message wasn't changed to adapt to the function of the new place) which may cause confusion when operators are reading the log messages. 
**org.apache.wicket.pageStore.AsynchronousPageStore.storePage
org.apache.wicket.pageStore.AsynchronousDataStore.storeData**
In the above two classes, there are two identical logging statements:
`log.debug("Storing synchronously page with id '{}' in session '{}'", id, sessionId);`
While in AsynchronousDataStore.storeData the code is dealing with **data** rather than **page**, so I changed the message from page to data.
2. In …
> Improve some logging statements

- wicket-core/src/main/java/org/apache/wicket/markup/html/form/upload/FileUpload.java
As of commons-fileupload 1.4, FileUtils.moveFile() is used to write the uploaded contents to the provided file. This implementation does not allow the destination to be present.
> WICKET-6630 Delete (temp) file before writing to it

- wicket-extensions/src/main/java/org/apache/wicket/extensions/ajax/markup/html/modal/res/modal.js
More Modal settings as promised in discussion of #294 . Sorry it took longer than I expected, was buried in work.
> Add more modal customizations

- wicket-examples/Dockerfile
because a new build target is 11
> update Dockerfile to point to tomcat:8.5-jre11

- wicket-examples/Dockerfile
As it was suggested in #360 by @solomax I tried to point to Tomcat 9 and it worked well.
> update Dockerfile to point to tomcat:9.0-jre11

- wicket-user-guide/src/main/asciidoc/testing/testing_1.adoc
The method `BaseWicketTester#startComponent(Component)` was removed in Wicket 7.0.0. See WICKET-5097
> Remove usage of deprecated method from test example

- archetypes/quickstart/src/main/resources/archetype-resources/src/main/webapp/WEB-INF/web.xml
As per https://www.oracle.com/webfolder/technetwork/jsc/xml/ns/javaee/index.html, any `web.xml` files referencing `web_app_3_1.xsd` or `web_app_4_0.xsd` should use the  `http://xmlns.jcp.org/xml/ns/javaee/` namespace, not the older `http://java.sun.com/xml/ns/javaee/` namespace.
Servers that validate the `web.xml` file (i.e. GlassFish) will fail to deploy as XML validation will fail due to the namespace used in the `web.xml` not matching the namespace used in the referenced .xsd
> [WICKET-6676] Fix for quickstart application not deploying to GlassFish

- archetypes/quickstart/src/main/resources/archetype-resources/src/main/webapp/WEB-INF/web.xml
Bit embarrassing this... tested the 8.6.0-SNAPSHOT last night and realized there is a typo on Oracle's JavaEE XSD page, which I copied into my commit.
The namespace in `web.xml` should be `http://xmlns.jcp.org/xml/ns/javaee` (without the trailing slash) not `http://xmlns.jcp.org/xml/ns/javaee/`
Apologies for this - my bad for not double checking
> [WICKET-6676A] Correction for WICKET-6676

- wicket-core/src/main/java/org/apache/wicket/markup/html/form/AutoLabelResolver.java
- wicket-core/src/main/java/org/apache/wicket/markup/html/form/ILabelProviderLocator.java
- wicket-core/src/test/java/org/apache/wicket/markup/html/form/AutoLabelLabelProviderLocatorTest$EditPage.html
- wicket-core/src/test/java/org/apache/wicket/markup/html/form/AutoLabelLabelProviderLocatorTest$ILabelProviderLocatorPanel1.html
- wicket-core/src/test/java/org/apache/wicket/markup/html/form/AutoLabelLabelProviderLocatorTest$ILabelProviderLocatorPanel2.html
- wicket-core/src/test/java/org/apache/wicket/markup/html/form/AutoLabelLabelProviderLocatorTest.java
make autolable funtionality more flexible by introducing a locator interface that allow to specify the component the wicket:for refers too
> make autolabel functionality more flexible by introducing a locator interface that allow to specify the component the wicket:for refers too

- wicket-core/src/main/java/org/apache/wicket/protocol/http/ClientProperties.java
- wicket-core/src/test/java/org/apache/wicket/protocol/http/ClientPropertiesTest.java
Fixes [WICKET-6689](https://issues.apache.org/jira/browse/WICKET-6689).
> WICKET-6689 fix ClientProperties.getTimezone() UTC-DST difference calculation.

- pom.xml
openjson: 1.0.10 to 1.0.11
commons-collectections4: 4.3 to 4.4
jackson: 2.9.8 to 2.9.9
jdk-serializable-functional: 1.8.5 to 1.8.6
> [WICKET-6698] Update dependency versions

- wicket-core/src/main/java/org/apache/wicket/core/util/objects/checker/CheckingObjectOutputStream.java
- wicket-core/src/test/java/org/apache/wicket/core/util/objects/checker/CheckingObjectOutputStreamPropertyChangeSupportTest.java
Do not check instances of PropertyChangeSupport whether they are Serializable because PropertyChangeSupport#writeObject() adds extra fields which confuse CheckingObjectOutputStream
> WICKET-6704 JavaSerializer.serialize causes the JVM crash !

- wicket-core/src/main/java/org/apache/wicket/Application.properties
- wicket-core/src/main/java/org/apache/wicket/Component.java
- wicket-core/src/main/java/org/apache/wicket/css/wicket-core.css
- wicket-core/src/main/java/org/apache/wicket/markup/html/form/Form.java
- wicket-core/src/test/java/org/apache/wicket/markup/html/form/FormDefaultButtonTestPage_expected.html
- wicket-core/src/test/java/org/apache/wicket/markup/html/form/FormMethodTestPage_expected.html
- wicket-core/src/test/java/org/apache/wicket/markup/html/form/pageWithParameters_expected.html
- wicket-extensions/src/main/java/org/apache/wicket/extensions/markup/html/repeater/data/table/filter/FilterForm.java
- wicket-extensions/src/test/java/org/apache/wicket/extensions/markup/html/repeater/data/table/filter/FilterFormTestPage_expected.html
This PR removes the inline styling and javascript from Form. The inline JS is moved to an event handler that is rendered in the head. The styling to the new core stylesheet under the `wicket--hidden-fields` class.
Note: previously it was possible to change the name of the class used to hide these fields, but I see no use case for that, so I decided to drop that functionality. This was implemented as part of WICKET-6527, in which a user asked to make these elements more easily styleable. For this it is not needed to change the name of the class and the current implementation suits that need.
> WICKET-6726: remove inline styling and javascript from Form

- wicket-core/src/main/java/org/apache/wicket/markup/html/form/SubmitLink.java
- wicket-core/src/test/java/org/apache/wicket/markup/html/form/validation/HomePage1_ExpectedResult.html
- wicket-core/src/test/java/org/apache/wicket/stateless/StatelessFormUrlTest.java
This PR moves the inline JS in SubmitLink to an event handler.
@martin-g You mentioned that we might need to call `setOutputMarkupId(true)`, but I haven't encountered any issues so far. As long as `renderHead` is called before `onComponentTag`, the id is rendered in the markup.
> WICKET-6731: Inline JS in SubmitLink

- testing/wicket-arquillian/pom.xml
[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …
> [SECURITY] Use HTTPS to resolve dependencies in Maven Build

- wicket-core/src/main/java/org/apache/wicket/MarkupContainer.java
Since there is only one pop() performed in hasNext() the iteration stops, if there are several nested container, when there are no additional childs in the parent container.
> Iteration stops with nested containers

- wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/WebSocketSettings.java
- wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/api/AbstractWebSocketProcessor.java
This PR adds a function `shouldNotifyOnErrorEvent` to `WebSocketSettings` that allows the user the decide which types of websocket errors should be broadcast. It serves the same purpose as the existing `shouldNotifyOnCloseEvent` function, i.e. to avoid deserializing the relevant page instance.
See https://issues.apache.org/jira/projects/WICKET/issues/WICKET-6759
> WICKET-6759 Support disabling error notification for websockets

- wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/api/BaseWebSocketBehavior.java
This PR allows users to customize the setup of websocket connections.
Websocket connections are currently opened when the DOM is ready. If users open tabs in the background, a new websocket connection is initialized for each tab. I want to defer connection creation to the moment when the user activates the tab.
Instead of adding yet another configuration parameter, I thought it might be better to give users full control of the initialization script by exposing `getWebSocketSetupScript`.
See https://issues.apache.org/jira/projects/WICKET/issues/WICKET-6762
> WICKET-6762 Allow users to customize websocket setup

- wicket-examples/src/main/java/org/apache/wicket/examples/websocket/HomePage.html
- wicket-examples/src/main/java/org/apache/wicket/examples/websocket/JSR356Application.java
- wicket-examples/src/main/java/org/apache/wicket/examples/websocket/WebSocketMultiTabResourceDemoPage.html
- wicket-examples/src/main/java/org/apache/wicket/examples/websocket/WebSocketMultiTabResourceDemoPage.java
- wicket-examples/src/main/java/org/apache/wicket/examples/websocket/charts/ChartUpdater.java
- wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/api/AbstractWebSocketProcessor.java
- wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/api/BaseWebSocketBehavior.java
- wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/api/registry/ResourceNameTokenKey.java
- wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/api/res/js/wicket-websocket-jquery.js
- wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/api/res/js/wicket-websocket-setup.js.tmpl
This PR adds an optional `resourceToken` to `BaseWebSocketBehavior` to support multiple websocket connections from the same session, i.e. from multiple browser tabs.
The token could be a UUID or some other calculated value.
Note: I'm not really happy about the name `resourceToken`. Maybe something like `connectionId` would be easier to understand.
See https://issues.apache.org/jira/browse/WICKET-6761
> WICKET-6761 Multiple websocket connections from the same session

- wicket-core/src/main/java/org/apache/wicket/ajax/AjaxChannel.java
Use string concatenation instead of formatting and replace switch with enum parameter.
https://issues.apache.org/jira/browse/WICKET-6777
> WICKET-6777 AjaxChannel.toString improvements

- wicket-core/src/main/java/org/apache/wicket/MarkupContainer.java
Clearing REMOVALS_KEY is a bottleneck in the current detach code. This PR prevents clearing the key by putting it behind a flag. This is a lot faster. The downside is that a flag is needed, and not many request flags are available.
> WICKET-6778: put REMOVALS_KEY metadata behind a flag

- wicket-util/src/main/java/org/apache/wicket/util/string/Strings.java
- wicket-util/src/test/java/org/apache/wicket/util/string/StringsTest.java
Checks for `Character.UNASSIGNED` instead of looking up non-chars in a set.
This solution more than doubles the throughput:
```
escapeMarkupHashSet        thrpt    5  395348,174 ± 48047,375  ops/s
escapeMarkupCharacterType  thrpt    5  847227,062 ± 13051,584  ops/s
```
https://issues.apache.org/jira/browse/WICKET-6788
> WICKET-6788 Improve performance of markup escaping

- wicket-core/src/main/java/org/apache/wicket/ajax/AjaxEventBehavior.java
This PR avoids splitting and joining ajax event names that do not contain whitespace.
Note: The splitting logic splits on "\s+" so this would also match tabs and newlines, but I think that checking for space is enough to return early.
See https://issues.apache.org/jira/browse/WICKET-6795
> WICKET-6795 Avoid splitting and joining ajax event names

- wicket-util/src/main/java/org/apache/wicket/util/encoding/UrlDecoder.java
- wicket-util/src/main/java/org/apache/wicket/util/encoding/UrlEncoder.java
- wicket-util/src/test/java/org/apache/wicket/util/encoding/UrlDecoderTest.java
- wicket-util/src/test/java/org/apache/wicket/util/encoding/UrlEncoderTest.java
This PR rewrites `UrlEncoder` and `UrlDecoder` based on Spring's `UriUtils` instead of `java.net.URLEncoder` and `java.net.URLDecoder`.
The new implementation is 30-500% faster depending on the use case. The biggest improvement is with encoding URLs that do not contain any character that requires escaping.
All tests pass and encoding should be fully backwards compatible.
For benchmark results, see the JIRA ticket.
See https://issues.apache.org/jira/browse/WICKET-6794
> WICKET-6794 Performance improvements for UrlEncoder and UrlDecoder

- wicket-core/src/main/java/org/apache/wicket/ajax/AjaxRequestHandler.java
While migrating my project (see [PR](https://github.com/ursjoss/scipamato/pull/177) there) from the mocking library [mockito](https://site.mockito.org/) to [mock](https://mockk.io/), I ran into weird performance issues. The build time jumped from roughly 20 minutes to eventually more than 4 hours. I took some effort improving various things in my own code (less mocking, more memory etc.) but did not bring it down considerably until I addressed a bottleneck I found in wicket.
`AjaxRequestHandler` maintains a collection of listeners in a `LinkedList`. When client code adds a new listener calling method `addListener`, it uses the collection's method `contains` to assert we don't add a listener to the collection twice. This doesn't scale well. For some reason, my setup with mockk seems to add …
> AjaxRequestHandler: Keep listeners in a LinkedHashSet instead of LinkedList for performance reason

- wicket-core/src/main/java/org/apache/wicket/protocol/http/CsrfPreventionRequestCycleListener.java
- wicket-core/src/main/java/org/apache/wicket/protocol/http/DefaultResourceIsolationPolicy.java
- wicket-core/src/main/java/org/apache/wicket/protocol/http/FetchMetadataRequestCycleListener.java
- wicket-core/src/main/java/org/apache/wicket/protocol/http/OriginBasedResourceIsolationPolicy.java
- wicket-core/src/main/java/org/apache/wicket/protocol/http/ResourceIsolationPolicy.java
- wicket-core/src/test/java/org/apache/wicket/protocol/http/CsrfPreventionRequestCycleListenerTest.java
- wicket-core/src/test/java/org/apache/wicket/protocol/http/FetchMetadataRequestCycleListenerTest.java
Hello Wicket devs,
This PR builds Fetch Metadata support on top of Wicket's existing CSRF protection, namely:
- If a request has `Sec-Fetch-*` headers (i.e. comes from a modern browser), Fetch Metadata will be preferred. Otherwise, we will fall back to using the existing cross-request checks.
- One default Resource Isolation Policy is provided based on [https://web.dev/fetch-metadata/](https://web.dev/fetch-metadata/), which prevents all major cross-site request forgery attacks.
- If the `Origin` or `Referer` headers are present, Fetch Metadata will apply the same exemptions as the existing Origin-based protection, i.e. allowing cross-origin requests from exempted origins.
- The `Vary` header has been added to responses through `onEndRequest` to ensure that any cached responses include …
> Wicket 6786: Add Fetch Metadata support

- wicket-core/src/main/java/org/apache/wicket/resource/ResourceUtil.java
- wicket-util/src/main/java/org/apache/wicket/util/string/Strings.java
This PR contains three minor performance optimizations:
- Precompile pattern for unescaping attributes in `ResourceUtil`
- Improve implementation of `Strings.join`
- Replace custom implementation of replace in `Strings.replaceAll` with JDK's `String.replace`
The implementation of `String.replace` in recent JDK versions is 2-3x faster than Wicket's current custom version:
Benchmark           |                        Mode |  Cnt      |    Score  | Units
StringsBenchmarks.replaceAllNew           | thrpt  |  3 |  26823346,762 |  ops/s
StringsBenchmarks.replaceAllOld        | thrpt  |  3 |  10294555,601 |  ops/s
`Strings.join` is about 40% faster after my minor tweaks:
Benchmark        |              Mode |  Cnt     | …
> String manipulation performance improvements

- wicket-core/src/main/java/org/apache/wicket/Behaviors.java
I made some initial tweaks to `Behaviors.getBehaviors()` in #422 but my profiler still shows a suspicious amount of allocation coming from this method.
I overlooked one big potential improvement when I tried to improve the method the last time:
The `ArrayList` that holds the behaviors is *always* initialized, even if we know that the component has no data. It is initialized with zero elements, but the overhead is still noticeable.
I adjusted the method to return early in case there is no data and I'm lazily initializing the list in case there are no behaviors or no behaviors of the requested type.
**Branch**
Benchmark    |                      Mode |  Cnt    |      Score     |      Units
Behaviors.noData       | thrpt | …
> WICKET-6773 More performance improvements for Behaviors

- wicket-core/src/main/java/org/apache/wicket/Behaviors.java
- wicket-core/src/main/java/org/apache/wicket/Component.java
We currently create a `Behaviors` instance for every invocation of its methods. While this is slightly "more OO" than a static utility class, it allocates hundreds of MiB per minute in my application.
This PR converts `Behaviors` into a static utility class.
See https://issues.apache.org/jira/browse/WICKET-6830
> WICKET-6830 Convert `Behaviors` into a static utility

- wicket-extensions/src/main/java/org/apache/wicket/extensions/markup/html/repeater/data/table/filter/FilterForm.java
We have the problem that by using a subclass of Filterform that is Ajax enabled we have to generate a different markup in onComponentTagBody. This PR would enable anyone to subclass Filterform and override the generated markup to something different.
> Make FilterForm#onComponentTagBody generated Markup overridable

- wicket-request/src/main/java/org/apache/wicket/request/mapper/parameter/PageParameters.java
- wicket-request/src/test/java/org/apache/wicket/request/mapper/parameter/PageParametersTest.java
This PR reduces allocations in `PageParameters.mergeWith`. As a side-effect, it increases throughput 4x.
It avoids allocating new collections where possible and attempts to initialize `namedParameters` with the correct size.
This method is called more than 1000 times per request in my application because we have a lot of mounted pages and resources and it is called for every single one of them.
**Master**
Benchmark    |                      Mode |  Cnt    |      Score     |      Units
ParameterBenchmarks.mergeWith                               |    thrpt  |  3 |  **1746723,436**  | ops/s
ParameterBenchmarks.mergeWith:·gc.alloc.rate.norm           |    thrpt  |  3 |     1600,190  | B/op …
> WICKET-6833 Reduce allocations for PageParameters.mergeWith

- wicket-request/src/main/java/org/apache/wicket/request/mapper/AbstractMapper.java
This is another small PR that significantly improves a "hot" method. 
Replacing `startsWith` and `endsWith` with `charAt` improves throughput by a factor of 3. It also prevents allocating a new String for non-placeholder segments because it does not use concatenation.
Benchmark    |                      Mode |  Cnt    |      Score     |      Units
MapperBenchmarks.getPlaceholderNew | thrpt  |  3 | `406808071,934` |  ops/s
MapperBenchmarks.getPlaceholderOld | thrpt  |  3  |    `132832411,311` |  ops/s
https://issues.apache.org/jira/browse/WICKET-6835
> WICKET-6835 Improve performance of `AbstractMapper.getPlaceholder`

- wicket-util/src/main/java/org/apache/wicket/util/string/Strings.java
- wicket-util/src/test/java/org/apache/wicket/util/string/StringsTest.java
This PR optimizes `String.split` for cases where the target string contains the separator 0 or 1 times.
**Branch**
Benchmark    |                      Mode |  Cnt    |      Score     |      Units
StringBenchmarks.split0                               |    thrpt  |  6 | `235703729,811`  |  ops/s
StringBenchmarks.split0:·gc.alloc.rate.norm           |    thrpt  |  6 |        `24,002`  |   B/op
StringBenchmarks.split1                               |    thrpt  |  6 |  `24061051,457`  |  ops/s
StringBenchmarks.split1:·gc.alloc.rate.norm           |    thrpt  |  6 |       `144,015`  |   B/op
StringBenchmarks.split2                               |    thrpt  |  6 |  `12975064,228`  |  ops/s …
> WICKET-6838 Improve performance of Strings.split

- wicket-core/src/main/java/org/apache/wicket/Component.java
- wicket-core/src/main/java/org/apache/wicket/MarkupContainer.java
- wicket-core/src/test/java/org/apache/wicket/ComponentTest.java
This PR aligns caching of `isVisibleInHierarchy` with `isEnabledInHierarchy`.
We are currently clearing the flag `RFLAG_VISIBLE_IN_HIERARCHY_SET` every time the visibility of a component changes, but we never use the flag. This PR adds `RFLAG_VISIBLE_IN_HIERARCHY_VALUE` to cache the result of the computation.
~~I had to change the type of `requestFlags` from `short` to `int` because all available 16 bits are already used up. If my understanding of the JVM memory layout is correct, this should *not* increase memory usage because all object fields use at least one slot of 32 bits anyways (see https://stackoverflow.com/a/27123302/441266).~~
I moved `RFLAG_HAS_REMOVALS` from `MarkupContainer` to `Component` so we do not accidentally assign the same bit to two different flags.
See …
> WICKET-6839 Use request flag for caching `isVisibleInHierarchy`

- NOTICE
- README.md
- pom.xml
- wicket-examples/src/main/resources/META-INF/NOTICE
- wicket-ioc/pom.xml
- wicket-ioc/src/main/java/module-info.java
- wicket-ioc/src/main/java/org/apache/wicket/proxy/LazyInitProxyFactory.java
- wicket-ioc/src/main/java/org/apache/wicket/proxy/objenesis/ObjenesisByteBuddyInterceptor.java
- wicket-ioc/src/main/java/org/apache/wicket/proxy/objenesis/ObjenesisCGLibInterceptor.java
- wicket-ioc/src/main/java/org/apache/wicket/proxy/objenesis/ObjenesisProxyFactory.java
- wicket-ioc/src/main/java/org/apache/wicket/proxy/objenesis/ObjenesisProxyReplacement.java
- wicket-ioc/src/test/java/org/apache/wicket/injection/util/MockDependency.java
- wicket-ioc/src/test/java/org/apache/wicket/proxy/LazyInitProxyFactoryTest.java
- wicket-ioc/src/test/java/org/apache/wicket/proxy/PackagePrivateConcreteObject.java
- wicket-ioc/src/test/java/org/apache/wicket/proxy/util/ConcreteObject.java
- wicket-jmx/pom.xml
- wicket-jmx/src/main/java/module-info.java
- wicket-jmx/src/main/java/org/apache/wicket/jmx/Initializer.java
- wicket-jmx/src/main/java/org/apache/wicket/jmx/wrapper/Application.java
- wicket-jmx/src/main/java/org/apache/wicket/jmx/wrapper/ApplicationSettings.java
- wicket-spring/src/test/java/org/apache/wicket/spring/injection/annot/SpringBeanWithGenericsTest.java
CGLib is not well maintained and it does not work with JDK 17+.
> WICKET-6913 Replace CGLib with ByteBuddy

- wicket-core/src/main/java/org/apache/wicket/protocol/http/MultipartFormComponentListener.java
- wicket-core/src/test/java/org/apache/wicket/protocol/http/MultipartFormComponentListenerPage.html
- wicket-core/src/test/java/org/apache/wicket/protocol/http/MultipartFormComponentListenerPage.java
- wicket-core/src/test/java/org/apache/wicket/protocol/http/MultipartFormComponentListenerTest.java
Currently, MultipartFormComponentListener ensures form enctype is
correct on the client-side when visibility for multipart-enabling
components is toggled. It does so by visiting all form components,
detecting multipart-enabling components and emitting javascript code
to refresh the encoding type on the client-side.
There are a few issues solved by this commit:
- The identified form component could be part of a hidden hierarchy.
This prevents finding it in the DOM, and using it's form attribute
to set the form enctype.
- There could be more than one form with multipart-enabling components
which would require an enctype refresh on the client-side.
This commit modifies MultipartFormComponentListener to find all forms,
ensure they are visible in the hierarchy, then visiting all form …
> WICKET-6921 Avoid updating hidden forms

- wicket-user-guide/src/main/asciidoc/forms2/forms2_9.adoc
- wicket-user-guide/src/main/asciidoc/i18n/i18n_5.adoc
- wicket-user-guide/src/main/asciidoc/keepControl/keepControl_1.adoc
In the Wicket User Guide the _adjective_ 'determinate' is being used as a verb. Those instances are now replaced with the actual verb 'to determine'.
Fixes WICKET-6931
> Change wrong 'to determinate' into correct 'to determine'

- wicket-core/src/main/java/org/apache/wicket/page/PartialPageUpdate.java
- wicket-examples/src/main/java/org/apache/wicket/examples/websocket/JSR356Application.java
- wicket-examples/src/main/java/org/apache/wicket/examples/websocket/JSR356Session.java
- wicket-examples/src/main/java/org/apache/wicket/examples/websocket/WebSocketBehaviorDemoPage.java
- wicket-examples/src/main/java/org/apache/wicket/examples/websocket/WebSocketMultiTabResourceDemoPage.java
- wicket-examples/src/main/java/org/apache/wicket/examples/websocket/WebSocketPushUpdateProgressDemoPage.html
- wicket-examples/src/main/java/org/apache/wicket/examples/websocket/WebSocketPushUpdateProgressDemoPage.java
- wicket-examples/src/main/java/org/apache/wicket/examples/websocket/progress/ProgressBarTogglePanel.html
- wicket-examples/src/main/java/org/apache/wicket/examples/websocket/progress/ProgressBarTogglePanel.java
- wicket-examples/src/main/java/org/apache/wicket/examples/websocket/progress/ProgressUpdater.java
- wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/api/AbstractWebSocketConnection.java
- wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/api/AbstractWebSocketProcessor.java
- wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/api/BaseWebSocketBehavior.java
- wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/api/WebSocketPushBroadcaster.java
- wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/api/WebSocketRequestHandler.java
- wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/api/registry/AbstractKey.java
- wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/api/registry/IKey.java
- wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/api/registry/IWebSocketConnectionRegistry.java
- wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/api/registry/PageIdKey.java
- wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/api/registry/ResourceNameKey.java
- wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/api/registry/ResourceNameTokenKey.java
- wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/api/registry/SimpleWebSocketConnectionRegistry.java
- wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/api/res/js/wicket-websocket-jquery.js
- wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/api/res/js/wicket-websocket-setup.js.tmpl
- wicket-native-websocket/wicket-native-websocket-core/src/main/java/org/apache/wicket/protocol/ws/util/tester/TestWebSocketProcessor.java
- wicket-native-websocket/wicket-native-websocket-core/src/test/java/org/apache/wicket/protocol/ws/util/tester/WebSocketTesterBehaviorTest.java
- wicket-native-websocket/wicket-native-websocket-javax/src/main/java/org/apache/wicket/protocol/ws/javax/JavaxWebSocketConnection.java
- wicket-native-websocket/wicket-native-websocket-javax/src/main/java/org/apache/wicket/protocol/ws/javax/WicketEndpoint.java
This PR adds some extra functionality to WS implementation. Not sure if this can be done in a cleaner way or a more general one. This adds.
- Allows to avoid sending "empty" web socket push messages (i.e. no components or scripts are added to it). The use case is user starts a background task and component listening for it are no longer in page. Thus events still go through a page but nothing is added to them.
- The pageClass is added as a variable to WS page related key. Use case? You want to deliver to a class of pages... or you want to start a task and leave a page, or open a new page and still receive events..
- I modified the examples to illustrate this.
> Wicket 6930 websocket improvements

- wicket-core/src/main/java/org/apache/wicket/protocol/http/MultipartFormComponentListener.java
- wicket-core/src/test/java/org/apache/wicket/protocol/http/MultipartFormComponentListenerBean.java
- wicket-core/src/test/java/org/apache/wicket/protocol/http/MultipartFormComponentListenerPage.java
Currently, MultipartFormComponentListener evaluates form visibility
before the configuration phase. This prevents code in onConfigure from
modifying the visibility of forms.
This ensures the listener evaluates the visibility during
onAfterRespond, which happens after the configuration phase.
The existing test case was modified to ensure modifications to the
visibility during the onConfigure phase is properly evaluated.
Closes: WICKET-6945
> WICKET-6945 Allow onConfigure to hide forms

- wicket-util/src/main/java/org/apache/wicket/util/lang/Args.java
- wicket-util/src/main/java/org/apache/wicket/util/string/Strings.java
- wicket-util/src/test/java/org/apache/wicket/util/string/StringsTest.java
This PR adds some micro-improvements for `Strings.isEmpty`.
`String.trim` is one of the hottest methods in my application. Most calls come from `Strings.isEmpty`, either called directly or via `Args.notEmpty`. It is called thousands of times during each request, so even minor improvements should make sense.
This PR applies two optimizations:
1. It adds overloaded methods for `Strings.isEmpty` and `Args.notEmpty` that take a `String` argument. The compiler seems to better inline the method when the exact parameter type is known at compile time. This results in about 5% performance improvement in most of my tests.
2. Before calling `String.trim`, the first character of the string is checked for whitespace. If it isn't whitespace, we can avoid calling `String.trim`. This optimization makes …
> WICKET-6952 Performance improvements for `Strings.isEmpty()`

- wicket-request/src/main/java/org/apache/wicket/request/mapper/info/ComponentInfo.java
This PR includes some micro optimizations for `ComponentInfo`:
- Pre-size `StringBuilders` when encoding and decoding component paths
- Return empty component path without further allocations
Pre-sizing the `StringBuilder` is about 10% faster if the path is longer than 16 characters.
https://issues.apache.org/jira/browse/WICKET-6960
> WICKET-6960 Avoid allocations when decoding and encoding `ComponentInfo`

- wicket-util/src/main/java/org/apache/wicket/util/string/Strings.java
Micro-optimization to prevent allocating a buffer when escaping an empty string.
https://issues.apache.org/jira/browse/WICKET-6964
> WICKET-6964 Do not allocate when escaping empty string

- wicket-native-websocket/wicket-native-websocket-javax/src/main/java/org/apache/wicket/protocol/ws/javax/WicketEndpoint.java
Make WicketEndpoint#REGISTERED_LISTENERS a static field.
Unregister the listener at Application#onBeforeDestroyed()
Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>
> WICKET-6965 Memory leak in WicketEndpoint

- wicket-core/src/main/java/org/apache/wicket/markup/html/border/BorderPanel.java
- wicket-core/src/main/java/org/apache/wicket/markup/html/form/FormComponentPanel.java
- wicket-core/src/main/java/org/apache/wicket/markup/html/panel/Panel.java
- wicket-core/src/main/java/org/apache/wicket/markup/html/panel/PanelMarkupSourcingStrategy.java
My latest production heapdump contained 2 million of these stateless objects. This PR introduces two singletons for `PanelMarkupSourcingStrategy` instead of allocating new objects for every component.
https://issues.apache.org/jira/browse/WICKET-6963
> WICKET-6963 Use singletons for PanelMarkupSourcingStrategy

- wicket-util/src/main/java/org/apache/wicket/util/listener/ListenerCollection.java
`ListenerCollection` has a note that states that the order is not guaranteed. This seems strange as the collection is simply a list and it even has a method to notify the listeners in reverse order. I suggest to change the comment and actually guarantee the order of notification to be in match with the order the listeners were added.
> Guarantee order of listener notifications

- wicket-native-websocket/wicket-native-websocket-javax/src/main/java/org/apache/wicket/protocol/ws/javax/WicketEndpoint.java
This PR stores the application name in a field when a websocket connection is opened, so we don't have to access the session during `onClose` and `onError`. When `onError` is called, the session may already be closed and request parameters can no longer be accessed.
https://issues.apache.org/jira/browse/WICKET-6965?focusedCommentId=17516488&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17516488
> WICKET-6965 Store application name to avoid accessing the session

- wicket-core/src/main/java/org/apache/wicket/Localizer.java
Suggestion: It would be very helpful to log the Resource key as well to easier identify the problem. 
Is this be security-sensitive? Can this be exploited somehow?
> [WICKET-6972] Add Resource key to be logged on Warning in Localizer.java

- wicket-native-websocket/wicket-native-websocket-javax/src/main/java/org/apache/wicket/protocol/ws/javax/JavaxUpgradeHttpRequest.java
In our application we have some URLs generated that use the servlet path. This fails when URLs are generated via WEB socket push. This fixes that problem
> [WICKET-6974] return correct context path

- wicket-core/src/main/java/org/apache/wicket/Component.java
- wicket-core/src/test/java/org/apache/wicket/behavior/SharedBehaviorTest.java
Incorporates improvement from #512 and fixes WICKET-6975.
https://issues.apache.org/jira/projects/WICKET/issues/WICKET-6975
> WICKET-6975 Ensure `behavior.renderHead()` is called only once

- wicket-core/src/main/java/org/apache/wicket/Component.java
- wicket-core/src/main/java/org/apache/wicket/markup/ComponentTag.java
Alternative implementation of #514 as suggested by @papegaaij.
https://issues.apache.org/jira/projects/WICKET/issues/WICKET-6976
> WICKET-6976 Avoid allocations when writing synthetic close tag

- wicket-core/src/main/java/org/apache/wicket/markup/html/border/BorderPanel.java
- wicket-core/src/main/java/org/apache/wicket/markup/html/form/FormComponentPanel.java
- wicket-core/src/main/java/org/apache/wicket/markup/html/panel/AssociatedMarkupSourcingStrategy.java
- wicket-core/src/main/java/org/apache/wicket/markup/html/panel/Panel.java
- wicket-core/src/main/java/org/apache/wicket/markup/html/panel/PanelMarkupSourcingStrategy.java
- wicket-core/src/test/java/org/apache/wicket/markup/parser/filter/HeaderSectionTest.java
This is my second attempt at using a singleton PanelMarkupSourcingStrategy for panels and borders.
My initial PR #503 had to be reverted, because I overlooked the non-final field `AssociatedMarkupSourcingStrategy#noMoreWicketHeadTagsAllowed` resulting in concurrency issues.
The field is questionable and the code related to it full of TODO and Why? comments. This PR gets rid of it. We have nearly two dozen tests for this code in HeaderSectionTest and the only result of deleting the field is a different error message in one of these tests.
The error message for the test changes from:
> \<wicket:head> tags are only allowed before \<body>, \</head>, \<wicket:panel> etc. tag
to the following message thrown from HtmlHeaderResolver: 
> Mis-placed \<wicket:head>. \<wicket:head> must be outside of …
> WICKET-6963 Singleton markup sourcing strategy (Take 2)

- wicket-core/src/main/java/org/apache/wicket/Component.java
- wicket-core/src/main/java/org/apache/wicket/markup/head/AbstractCssReferenceHeaderItem.java
- wicket-core/src/main/java/org/apache/wicket/markup/head/AbstractJavaScriptReferenceHeaderItem.java
- wicket-core/src/main/java/org/apache/wicket/markup/head/CssReferenceHeaderItem.java
- wicket-core/src/main/java/org/apache/wicket/markup/head/CssUrlReferenceHeaderItem.java
- wicket-core/src/main/java/org/apache/wicket/markup/head/JavaScriptContentHeaderItem.java
- wicket-core/src/main/java/org/apache/wicket/markup/head/JavaScriptReferenceHeaderItem.java
- wicket-core/src/main/java/org/apache/wicket/markup/head/JavaScriptUrlReferenceHeaderItem.java
- wicket-core/src/main/java/org/apache/wicket/markup/head/MetaDataHeaderItem.java
- wicket-core/src/main/java/org/apache/wicket/markup/head/OnEventHeaderItem.java
- wicket-core/src/main/java/org/apache/wicket/request/resource/ResourceReference.java
AbstractJavaScriptReferenceHeaderItem and children use a simple, but somewhat expensive, hashcode computation.   We can obtain the same result using much less time, and avoid all creation of garbage objects.   This is a substantial memory savings on complex pages with a large component hierarchy.
> WICKET-6977 More efficient hashcode computations

- wicket-request/src/main/java/org/apache/wicket/request/mapper/info/ComponentInfo.java
- wicket-request/src/main/java/org/apache/wicket/request/mapper/info/PageComponentInfo.java
- wicket-request/src/main/java/org/apache/wicket/request/mapper/info/PageInfo.java
These are some simple improvements that reduces unneeded String allocation for some Wicket objects, and sizes a 
StringBuilder sensibly to avoid a resize operation on every use.
I suspect there are some other patterns like this in the code.   These are the ones that stood out in our applications.
> WICKET-6979 Cut back slightly on some String instance creation in PageInfo and friends.

- wicket-core/src/main/java/org/apache/wicket/core/request/handler/ListenerRequestHandler.java
ListenerRequestHandler currently forces initialization of pages. For already initialized stateful pages, this traverses the entire component hierarchy. For large pages, this can be a costly operation.
Forcing page initialization was originally introduced in [WICKET-4116](https://issues.apache.org/jira/browse/WICKET-4116) in [this commit](https://github.com/apache/wicket/commit/42a436235ff4ed60f1eaa0f406ea96aa63a6eb2e) to fix an issue with expired pages and checking for statelessness. In [WICKET-5083](https://issues.apache.org/jira/browse/WICKET-5083), [this commit](https://github.com/apache/wicket/commit/34f43642195058f375d161dbb7cec58b40711423) added the same  initialization directly to `Page.isPageStateless()`, but invokes it only when necessary.
I think we can get rid of the …
> WICKET-6982 Do not force page initialization in `ListenerRequestHandler`.

- wicket-core/src/main/java/org/apache/wicket/protocol/http/AbstractRequestLogger.java
- wicket-core/src/main/java/org/apache/wicket/protocol/http/RequestLogger.java
The http RequestLogger is very expensive. In our system, we see almost 4kb of memory allocation in this code to create a logging String that is ~700 bytes long, per logging message being created. 
- the use of AppendingStringBuffer immediately doubles the memory requirement compared to StringBuilder as the former treats
all characters as UTF16.   The log messages here appear to be mostly Latin1.
- Calls to getRequestHandlerString allocate an AppendingStringBuffer, resize it once, and then call toString().
This results in nearly 1KB of garbage object creation (along with 5 objects) and repeated data copies per call.
- Portions of the final String will have been copied up to 5 times in the accumulation of the logging String.
Much better would be to have a single StringBuilder that is used …
> The http RequestLogger is very expensive. 

- wicket-core/src/main/java/org/apache/wicket/Application.java
By replacing the datastructure for Application class's metaData field
with a ConcurrentHashMap we can remove the synchronization on the
application instance and speed up lookups of the metadata. For at least
one application this will remove 50% of all blocking calls.
(cherry picked from commit 8c770c4337cc2649385aea49f02d29a357ac7acf)
> WICKET-7002 Remove blocking code from Application#get/setMetaData (9.x)

- wicket-core/src/main/java/org/apache/wicket/Application.java
By replacing the datastructure for Application class's metaData field
with a ConcurrentHashMap we can remove the synchronization on the
application instance and speed up lookups of the metadata. For at least
one application this will remove 50% of all blocking calls.
(cherry picked from commit 8c770c4337cc2649385aea49f02d29a357ac7acf)
> WICKET-7002 Remove blocking code from Application#get/setMetaData (8.x)

- wicket-core/src/main/java/org/apache/wicket/Application.java
By replacing the datastructure for Application class's metaData field
with a ConcurrentHashMap we can remove the synchronization on the
application instance and speed up lookups of the metadata. For at least
one application this will remove 50% of all blocking calls.
> WICKET-7002 Remove blocking code from Application#get/setMetaData (10.x)

- archetypes/quickstart/src/main/resources/archetype-resources/src/test/jetty/jetty.xml
Make example Jetty configuration expose less information about the server.
> Fix apache/wicket#WICKET-7004

- wicket-bean-validation/src/test/java/org/apache/wicket/bean/validation/DefaultPropertyResolverTest.java
- wicket-devutils/src/test/java/org/apache/wicket/devutils/inspector/SessionSizeModelTest.java
- wicket-extensions/src/test/java/org/apache/wicket/extensions/markup/html/repeater/data/table/DataTableTest.java
- wicket-extensions/src/test/java/org/apache/wicket/extensions/markup/html/repeater/util/TreeModelProviderTest.java
- wicket-guice/src/test/java/org/apache/wicket/guice/AbstractInjectorTest.java
- wicket-spring/src/test/java/org/apache/wicket/spring/FieldBeansCollectorTest.java
- wicket-util/src/test/java/org/apache/wicket/util/size/BytesTest.java
- wicket-util/src/test/java/org/apache/wicket/util/string/AppendingStringBufferTest.java
- wicket-util/src/test/java/org/apache/wicket/util/string/PrependingStringBufferTest.java
- wicket-util/src/test/java/org/apache/wicket/util/string/StringValueTest.java
- wicket-util/src/test/java/org/apache/wicket/util/value/AttributeMapTest.java
- wicket-util/src/test/java/org/apache/wicket/util/value/ValueMapTest.java
Ran the Clean Up Assertions recipe from the OpenRewrite project (https://docs.openrewrite.org/reference/recipes/java/testing/junit5/cleanupassertions version 1.30.0).
Had to do 1 manual change to SpringBeanTest to make sure the == bean check was not replaced by assertEquals
> WICKET-7011: Cleanup JUnit 5 assertions

- wicket-core/src/main/java/org/apache/wicket/util/tester/BaseWicketTester.java
- wicket-core/src/test/java/org/apache/wicket/util/tester/BaseWicketTesterTest.java
- wicket-core/src/test/java/org/apache/wicket/util/tester/DemoPanel$DemoPanelB.html
- wicket-core/src/test/java/org/apache/wicket/util/tester/DemoPanel.html
- wicket-core/src/test/java/org/apache/wicket/util/tester/DemoPanel.java
- wicket-spring/src/test/java/org/apache/wicket/spring/injection/bytebuddy/ParallelInjectionTest.java
- Add getAllComponentsFromLastRenderedPageByWicketId and getFirstComponentFromLastRenderedPageByWicketId to BaseWicketTester
It has always bothered me that unlike TagTester BaseWicketTester has no way of finding Components by Wicket ID
> [WICKET-7030] Add Convenience Methods to BaseWicketTester

- pom.xml
- wicket-migration/pom.xml
- wicket-migration/src/main/java/org/apache/wicket/Main.java
- wicket-migration/src/main/resources/META-INF/rewrite/wicket.yml
- wicket-migration/src/test/java/org/apache/wicket/migration/MigrateToWicket10Test.java
Makes it easier for users to adopt Apache Wicket 10. https://issues.apache.org/jira/browse/WICKET-7029
Migration then comes down to executing a single command:
```shell
mvn -U org.openrewrite.maven:rewrite-maven-plugin:run \
-Drewrite.recipeArtifactCoordinates=org.apache.wicket:wicket-migration:LATEST \
-DactiveRecipes=org.apache.wicket.BestPractices
```
> WICKET-7029 Add wicket-migration module

- wicket-core/src/main/java/org/apache/wicket/Component.java
- wicket-core/src/main/java/org/apache/wicket/response/LazyStringResponse.java
This PR avoids unnecessary allocation of `AppendingStringBuffer` for a `StringResponse` that is never written to.
In our case, 99% of the allocations in `Component#internalRenderHead` can be avoided in this way.
I'm not sure if we should add `LazyStringResponse` as a separate class, or simply make the existing `StringResponse` lazy. It is used in a lot of places, so we might avoid more allocations if we changed the default implementation.
See https://issues.apache.org/jira/browse/WICKET-7041
> WICKET-7041 Introduce `LazyStringResponse` to avoid unnecessary allocations

- wicket-core/src/main/java/org/apache/wicket/ajax/AjaxOnDomReadyClientInfoBehavior.java
- wicket-examples/src/main/java/org/apache/wicket/examples/ajaxhellowbrowserondomready/AjaxHelloBrowserOnDomReady.html
- wicket-examples/src/main/java/org/apache/wicket/examples/ajaxhellowbrowserondomready/AjaxHelloBrowserOnDomReady.java
- wicket-examples/src/main/java/org/apache/wicket/examples/ajaxhellowbrowserondomready/HelloBrowserOnDomReadyApplication.java
- wicket-examples/src/main/resources/org/apache/wicket/examples/homepage/HomePage.html
- wicket-examples/src/main/webapp/WEB-INF/web.xml
AjaxClientInfoBehavior is AJAX timer based. This seems not to work reliable in all situations. We add a AjaxOnDomReadyClientInfoBehavior that uses DOMREADY and seems to work more reliable.
> [WICKET-7048] add AjaxOnDomReadyClientInfoBehavior

- wicket-core/src/main/java/org/apache/wicket/markup/head/filter/FilteringHeaderResponse.java
This PR avoids allocating `AppendingStringBuffer` for empty header buckets in `FilteringHeaderResponse`.
It targets 9.x because in 10, all string responses will be lazy by default (#574).
> WICKET-7049 Avoid allocating a string buffer for empty header buckets

- wicket-core/src/main/java/org/apache/wicket/core/request/mapper/AbstractBookmarkableMapper.java
- wicket-request/src/main/java/org/apache/wicket/request/mapper/parameter/PageParameters.java
This PR avoids creating a `TreeSet` in `PageParameters.getNamedKeys()` when we do not actually need the contents of the set.
The empty check is 50x faster. The contains check is 5-10x faster for page parameters of a reasonable size. 
If somebody is using page parameters with dozens or hundreds of elements, we could still fall back to the `TreeSet`, but I highly doubt it.
https://issues.apache.org/jira/browse/WICKET-7045
> WICKET-7045 PageParameter optimizations

- wicket-util/src/main/java/org/apache/wicket/util/string/Strings.java
This PR initializes the string buffer for Strings#toMultilineMarkup to a capacity that should avoid resizing the buffer in most cases.
https://issues.apache.org/jira/browse/WICKET-7047
> WICKET-7047 Improve initial buffer capacity for multiline-markup

- wicket-util/src/main/java/org/apache/wicket/util/thread/Task.java
- Do not log an error if a task is interrupted while sleeping
- Do log a trace message when the task has been stopped
https://issues.apache.org/jira/browse/WICKET-7052
> [WICKET-7052] Interrupting a task should not be logged as an error

- wicket-core/src/main/java/org/apache/wicket/pageStore/InSessionPageStore.java
- wicket-core/src/test/java/org/apache/wicket/pageStore/InSessionPageStoreConcurrencyTest.java
InSessionPageStore.SessionData#pages is a LinkedList. LinkedList is not thread-safe and keeps a rather complex state as it has to keep track of first and last element and the list size. The combination leads to some fragility. For instance, if multiple threads concurrently remove the same element, both operations will succeed (and remove the same element) but the individually stored list size will get reduced twice. In the case of WICKET-6966 and WICKET-7013 this has happened. The exception message states that the current list size is -1. 
InSessionPageStore.SessionData#pages is only accessed in InSessionPageStore.SessionData itself and InSessionPageStore.CountLimitedData. Most accesses are in synchronized instance methods. Unfortunately …
> WICKET-6966, WICKET-7013: prevent unsynchronized access to pages

- wicket-core/src/test/java/org/apache/wicket/ApplicationSettingsTest.java
- wicket-core/src/test/java/org/apache/wicket/markup/MarkupParserTest.java
I am working on research that investigates test smell refactoring in which we identify alternative implementations of test cases, study how commonly used these refactorings are, and assess how acceptable they are in practice.
The first smell is when inappropriate assertions are used, while there exist better alternatives. For example, in [throws Exception using assertThrows](https://github.com/apache/wicket/commit/d667bafbb8081b87fc6dc764f7fc895b066b96d7), I refactored `assertTrue(img.getName().equals("img"));` using `assertEquals(img.getName(), "img");`.
The second smell is when exception handling can alternatively be implemented using assertion rather than annotation. For example, in [ApplicationSettingsTest.java](https://github.com/apache/wicket/commit/d667bafbb8081b87fc6dc764f7fc895b06 …
> [WICKET-7069] Refactor `assertTrue(equals())` using `assertEquals`

- .github/workflows/maven.yml
- pom.xml
- wicket-migration/pom.xml
- wicket-util/src/test/java/org/apache/wicket/util/convert/converter/LocalDateTimeConverterTest.java
- wicket-util/src/test/java/org/apache/wicket/util/convert/converter/ZonedDateTimeConverterTest.java
- wicket-util/src/test/java/org/apache/wicket/util/file/FilesTest.java
Update Maven in CI to 3.9.4 (latest stable)
> Build and test with JDK 17 & 21

- wicket-core/src/main/java/org/apache/wicket/protocol/http/servlet/ServletWebResponse.java
CrossOriginOpenerPolicyRequestCycleListener attempts to write headers to a response that is already committed. It contains logic to prevent setting of headers when a response does not support them, but the implementation for ServletWebResponse always returns true.
This PR modifies ServletWebResponse to check if the underlying HttpServletResponse has already been committed.
> WICKET-7075: Only support headers on uncommitted response

- wicket-core/src/main/java/org/apache/wicket/markup/head/JavaScriptReferenceType.java
Implement classes newly added as Serializable to be able to store in cache or to be serialized.
Fix https://issues.apache.org/jira/projects/WICKET/issues/WICKET-7076?filter=allissues
> JavascriptReferenceType: Implement Serializable

- wicket-core/src/main/java/org/apache/wicket/ajax/res/js/wicket-ajax-jquery.js
- wicket-core/src/main/java/org/apache/wicket/markup/html/form/Form.java
[WICKET-7083](https://issues.apache.org/jira/browse/WICKET-7083)
Instead of using jQuery's event triggering for the submit event, use the [browsers built-in functionality](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/requestSubmit) which, as a bonus, will also perform client side validation (such as the `required` attribute).
> WICKET-7083: Trigger client side validation when using SubmitLinks

- wicket-core/src/main/java/org/apache/wicket/ajax/attributes/AjaxRequestAttributes.java
- wicket-core/src/main/java/org/apache/wicket/markup/html/form/FormComponent.java
In the test getSetUnmodifiableSet and getSetNullList, we use a set to intitialize our choice, and assume it will have the order with getDefaultModelObjectAsString to be [A, B], but this is not necessary true according to [Oracle's official document](https://docs.oracle.com/javase/8/docs/api/java/util/HashSet.html#:~:text=It%20makes%20no%20guarantees%20as%20to%20the%20iteration%20order%20of%20the%20set%3B%20in%20particular)
For the test renderAjaxAttributes, we create the Json string from the AjaxRequestAttributes and assume the order of the fields in tests which is not true because it serialize from extraParameters which was a HashMap, which did not guarantee any order and will cause non-deterministic when we change the environments like JDK version. Also the LinkedHashMap is designed …
> WICKET-7088: Improve test reliability by resolving nondeterministic order of Set and Map 

- pom.xml
- wicket-auth-roles/pom.xml
- wicket-bean-validation/pom.xml
- wicket-cdi/pom.xml
- wicket-core/pom.xml
- wicket-devutils/pom.xml
- wicket-experimental/wicket-metrics/pom.xml
- wicket-extensions-tester/pom.xml
- wicket-extensions/pom.xml
- wicket-guice/pom.xml
- wicket-ioc/pom.xml
- wicket-jmx/pom.xml
- wicket-native-websocket/wicket-native-websocket-core/pom.xml
- wicket-native-websocket/wicket-native-websocket-javax/pom.xml
- wicket-native-websocket/wicket-native-websocket-tester/pom.xml
- wicket-request/pom.xml
- wicket-spring/pom.xml
- wicket-tester/pom.xml
- wicket-util/pom.xml
- wicket-velocity/pom.xml
In addition to reprocible builds, this should also result in timestamps being set on files in jars.
> WICKET-7090: add outputTimestamp property to enable reproducible builds

- wicket-migration/src/main/resources/META-INF/rewrite/wicket.yml
Adds the new dependency that was added as part of WICKET-7072
- https://issues.apache.org/jira/browse/WICKET-7072
- https://issues.apache.org/jira/browse/WICKET-7029
> WICKET-7029 Add wicket-tester dependency during migration

- wicket-util/src/main/java/org/apache/wicket/util/resource/XSLTResourceStream.java
Make the javax.xml.transform.TransformerFactory configurable so that features can be set.
> feat: configurable transformer factory

- wicket-core/src/main/java/org/apache/wicket/page/CouldNotLockPageException.java
- wicket-core/src/main/java/org/apache/wicket/page/DefaultPageLockManager.java
Adds the stack trace of the thread holding the lock of a page in case of
a timeout trying to acquire a lock. This is quite handy when trying to
figure out what caused the CouldNotLockPageException without having to
go sift through logs.
> WICKET-7110 Feat: add lock holding stack to CouldNotLockPageException

- wicket-core/src/main/java/org/apache/wicket/Component.java
- wicket-core/src/test/java/org/apache/wicket/settings/ExceptionSettingsNotRenderableErrorStrategyTest.java
WICKET-7112
The error messages in the Component class have been augmented with more detailed information. These include class type, parent markup ID, parent relative path, and the original URL. This is to give a more comprehensive context surrounding the error, aiding debugging and issue resolution.
> WICKET-7112 Expand error messages in Component class

- wicket-core-tests/src/test/java/org/apache/wicket/ComponentOnConfigureTest.java
- wicket-core-tests/src/test/java/org/apache/wicket/markup/repeater/AbstractPageableViewTest.java
- wicket-core-tests/src/test/java/org/apache/wicket/pageStore/AbstractPersistentPageStoreTest.java
- wicket-core-tests/src/test/java/org/apache/wicket/resource/FileSystemResourceReferenceTest.java
- wicket-util/src/test/java/org/apache/wicket/util/string/StringsTest.java
Fixes https://issues.apache.org/jira/browse/WICKET-7119
Some unit tests are non-idempotent, as they pass in the first run but fail in the second run in the same environment. A fix is necessary since unit tests shall be self-contained, ensuring that the state of the system under test is consistent at the beginning of each test. In practice, fixing non-idempotent tests can help proactively avoid state pollution that results in test order dependency (which could cause problems under test selection, prioritization or parallelization).
Using the `NIOInspector` plugin that supports rerunning JUnit tests in the same environment. Use `org.apache.wicket.util.string.StringsTest#stripJSessionId` as an example:
```
cd wicket-util
mvn edu.illinois:NIOInspector:rerun …
```
> [WICKET-7119] Fixed non-idempotent unit tests

- wicket-extensions/src/main/java/org/apache/wicket/extensions/ajax/markup/html/autocomplete/AutoCompleteTextField.java
- wicket-extensions/src/main/java/org/apache/wicket/extensions/ajax/markup/html/autocomplete/wicket-autocomplete.js
Autocomplete textfields arent read properly by a screenreader when selection the options with arrow keys. This PR adresses that issue.
**input must have**
role="combobox"
aria-expanded="true/false"
autocomplete="off"
aria-autocomplete="list"
aria-controls=$ID
**ul must have**
role="listbox"
id=$ID
**li must have**
role="option"
aria-posinset: Item Position
aria-setsize: length of List
aria-selected: true when selected / false when not
tabindex="-1"
> [WICKET-7120] - Make AutoCompleteTextField more Accessible

- wicket-cdi/src/main/resources/META-INF/beans.xml
The latest release of Wicket-CDI contains bean archive descriptor referencing legacy JavaEE namespace. This pull request changes the descriptor to use Jakarta namespace.
[WICKET-7122](https://issues.apache.org/jira/browse/WICKET-7122)
> WICKET-7122 Upgrade beans.xml descriptor in Wicket CDI

- wicket-core-tests/src/test/java/org/apache/wicket/markup/html/form/FormDefaultButtonTestPage_expected.html
- wicket-core-tests/src/test/java/org/apache/wicket/markup/html/form/FormHierarchyDefaultButtonTestPage.html
- wicket-core-tests/src/test/java/org/apache/wicket/markup/html/form/FormHierarchyDefaultButtonTestPage.java
- wicket-core-tests/src/test/java/org/apache/wicket/markup/html/form/FormHierarchyDefaultButtonTestPage_expected.html
- wicket-core-tests/src/test/java/org/apache/wicket/markup/html/form/FormTest.java
- wicket-core/src/main/java/org/apache/wicket/markup/html/form/Form.java
- wicket-examples/src/main/java/org/apache/wicket/examples/forminput/FormInput.html
- wicket-examples/src/main/java/org/apache/wicket/examples/forminput/FormInput.java
- wicket-examples/src/main/java/org/apache/wicket/examples/forminput/FormInput.properties
- wicket-examples/src/main/java/org/apache/wicket/examples/forminput/forminput.css
- default form submit can now be set one per form (not form hierarchy)
- hidden input submit in root form now not needed, everything handled in JS
- click invocation mostly reused old part of javascript
- tests green
One thing that I'm missing but couldn't figure out was to write test with form hierarchy (parent/child form) with inputs and simulate filling text field and hitting "enter"...
> WICKET-7123 default form submit can now be set one per form

- wicket-extensions/src/main/java/org/apache/wicket/extensions/ajax/markup/html/autocomplete/wicket-autocomplete.js
Improved accessibility support with the following changes
- The up and down arrow keys in the auto-complete dropdown should not move the cursor to the start or end of the text field
- aria-expanded should be set on the input element to indicate whether the dropdown is expanded or collapsed
- aria-selected should be set on the element that is currently selected in the dropdown
- aria-activedescendant attribute should be used on the input field, pointing to the currently selected item in the dropdown. This allows screen readers to track the active selection in the list.
- aria-live should not be set on the dropdown as it will cause a screen reader to read out everything in the dropdown, which disrupts the navigaition workflow
> WICKET-7131 Improved accessibility and screen reader support

- wicket-extensions/src/main/java/org/apache/wicket/extensions/ajax/markup/html/autocomplete/wicket-autocomplete.js
When using tab to leave an auto complete field without anything selected the editing does not work immediately if returning to the field. One will need to type at least one character before the autocomplete will trigger an opening of the dropdown.
> WICKET-7132 Tabbing from AutoComplete fields and back doesn't work as expected

- wicket-core-tests/src/test/java/org/apache/wicket/markup/html/form/FormVisitTest.java
- wicket-core/src/main/java/org/apache/wicket/markup/html/form/Form.java
- wicket-core/src/main/java/org/apache/wicket/markup/html/form/FormComponent.java
visiting
- removing traversal signaling dead code
- test if form validator dependent components are enabled and form participants
- internalMarkFormComponentsValid in postorder
- updateNestedFormComponentModels in postorder
- internalOnValidateModelObjects in porstorder
> WICKET-3899 testing Form#wantSubmitOnParentFormSubmit in the form

- wicket-extensions/src/main/java/org/apache/wicket/extensions/ajax/markup/html/autocomplete/AbstractAutoCompleteBehavior.java
- wicket-extensions/src/main/java/org/apache/wicket/extensions/ajax/markup/html/autocomplete/AutoCompleteSettings.java
- wicket-extensions/src/main/java/org/apache/wicket/extensions/ajax/markup/html/autocomplete/wicket-autocomplete.js
We need the ability to prevent the autocomplete from moving the focus to the next component when the user press "Tab". The marked item should be selected but the focus should go back to the autocomplete input field.
> WICKET-7133 Ability move focus back to the autocomplete field when selecting an item using the Tab key

- LICENSE
The Apache 2.0 license on the website shows that it ends after "END OF TERMS AND CONDITIONS" https://www.apache.org/licenses/LICENSE-2.0
This text exists because it's been mistakenly copied and pasted from https://www.apache.org/licenses/LICENSE-2.0.txt where it includes placeholder text and the intent seems to be reproducing the application instructions as seen on https://www.apache.org/licenses/LICENSE-2.0 rather than as text that's intended to be included in the license.
The text removed in this PR diverges slightly from the text on https://www.apache.org/licenses/LICENSE-2.0#apply
> How to apply the Apache License to your work
>
> Include a copy of the Apache License, typically in a file called LICENSE, in your work, and consider also including a NOTICE file that references the …
> Remove extra text from license

- wicket-core/src/main/java/org/apache/wicket/protocol/http/OriginResourceIsolationPolicy.java
- wicket-core/src/main/java/org/apache/wicket/util/tester/BaseWicketTester.java
- wicket-core/src/test/java/org/apache/wicket/core/util/tester/WicketTesterTest.java
The parameter order for the checks is: object, message. The calls passed the parameters in the wrong order.
> WICKET-7147: reversed order of parameters to `null` check methods

- wicket-core/src/main/java/org/apache/wicket/markup/html/form/Form.java
- centralizing form processing code inside the visit
- replacing form#isSubmitted with form#isVisible/EnabledInHierarchy
> WICKET-7134 Form code refactoring

- wicket-core-tests/src/test/java/org/apache/wicket/markup/html/JsCssReferenceHeaderItemTest.java
- wicket-core/src/main/java/org/apache/wicket/markup/head/AbstractCssReferenceHeaderItem.java
- wicket-core/src/main/java/org/apache/wicket/markup/head/CssReferenceHeaderItem.java
- wicket-core/src/main/java/org/apache/wicket/markup/head/JavaScriptReferenceHeaderItem.java
- wicket-core/src/main/java/org/apache/wicket/request/resource/ResourceReference.java
**Synopsis**  
Added two new variables to the ResourceReference class.  Added code to use these values in both the JavaScriptReferenceHeaderItem and CssReferenceHeaderItem classes.  Also fixed a bug with the AbstractCssReferenceHeaderItem class where it was directly accessing the identity and crossOrigin values directly instead of going through accessor methods.
**In-depth Detail**:
It is easy to create the integrity and cross origin values needed when the we have the control over the creation of the JavaScriptHeaderItem or CssReferenceHeaderItem.  It becomes much more difficult when there are resources that are created and then stored in wicket framework classes (whether resource references are framework or user created), because these resources are used later by the framework when it …
> WICKET-7149: Add Integrity and CrossOrigin values to ResourceReference and related code

- wicket-request/pom.xml
- wicket-request/src/main/java/org/apache/wicket/request/http/handler/RedirectRequestHandler.java
- wicket-request/src/test/java/org/apache/wicket/request/http/handler/RedirectRequestHandlerTest.java
https://issues.apache.org/jira/browse/WICKET-7152
> WICKET-7152: HTTP-StatusCodes 307 and 308 now supported by RedirectRequestHandler
